name: retail_sync
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

# ----- Packages ----- #
dependencies:
  
  flutter:
    sdk: flutter
  # State Management
  get: ^4.6.6
  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  # ----- Local Assets ----- #
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/logos/
    - assets/fonts/
    - assets/videos/

  # ----- Local Fonts ----- #
  fonts:
  - family: Poppins
    fonts:
      - asset: assets/fonts/Poppins-Regular.ttf
        weight: 300
      - asset: assets/fonts/Poppins-Italic.ttf
        style: italic
      - asset: assets/fonts/Poppins-Medium.ttf
        weight: 400
      - asset: assets/fonts/Poppins-MediumItalic.ttf
        weight: 400
        style: italic
      - asset: assets/fonts/Poppins-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Poppins-Bold.ttf
        weight: 800
